image: atlassian/default-image:4

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          deployment: production
          image: ngearing/git-ftp
          script:
            - git ftp push -u $FTP_USER -p $FTP_PASS $FTP_URL
